version: '3'

services:
  nginx:    
    image: 'nginx:latest'
    ports:
      - '${HTTP_PORT}:80'
    volumes:
      - './docker/nginx/conf.d.prepare:/etc/nginx/conf.d'
      - '${PROJECT_WEB_DIR}:/usr/share/nginx/html'    