version: '3'

services:
  webserver:
    image: 'nginx:alpine'    
    working_dir: /var/www/html
    volumes:      
      - '${PROJECT_WEB_DIR}:/var/www/html'
      - './docker/nginx/nginx-production.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${WEBSERVER_PORT}:80'      
    links:
      - php-fpm    
    depends_on:
      - php-fpm
  php-fpm:
    image: 'amarinboonkirt/php72-fpm-stretch'
    build:
        context: ./docker/php-fpm
        dockerfile: Dockerfile    
        args:
          - TZ=${TZ}
          - LOCALE=${LOCALE} 
          - WEB_UID=${WEB_UID}
          - WEB_GID=${WEB_GID}    
    working_dir: /var/www/html
    volumes:      
      - '${PROJECT_WEB_DIR}:/var/www/html'      
      - './docker/php-fpm/php-ini-production.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini:ro'
    links:
      - mariadb      
    depends_on:
      - mariadb
  mariadb:
    image: 'mariadb:10.4'    
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}    
    volumes:
      - './storage/mysql:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin    
    links:
      - mariadb
    depends_on:
      - mariadb  
    environment:      
      - PMA_HOST=mariadb
    ports:
      - '${PHPMYADMIN_PORT}:80'
    volumes:
      - /sessions