version: '3'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    volumes:   
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - '${PROJECT_WEB_DIR}:/usr/share/nginx/html'
      - './storage/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem'      
      - './storage/etc/letsencrypt/live/${HOST_NAME}/fullchain.pem:/etc/letsencrypt/live/${PUBLIC_HOST_NAME}/fullchain.pem'
      - './storage/etc/letsencrypt/live/${HOST_NAME}/privkey.pem:/etc/letsencrypt/live/${PUBLIC_HOST_NAME}/privkey.pem'
    links:
      - php-fpm    
    depends_on:
      - php-fpm
    restart: always
  php-fpm:
    image: 'amarinboonkirt/php72-fpm-stretch'  
    working_dir: /var/www/html
    volumes:      
      - '${PROJECT_WEB_DIR}:/var/www/html'      
      - './docker/php-fpm/php-ini-production.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini:ro'
    links:
      - mariadb      
    depends_on:
      - mariadb
    restart: always
  mariadb:
    image: 'mariadb:10.4'    
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}    
    volumes:
      - './storage/mysql:/var/lib/mysql'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    restart: always
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin    
    links:
      - mariadb
    depends_on:
      - mariadb  
    environment:      
      - PMA_HOST=mariadb
    ports:
      - '${PHPMYADMIN_PORT}:80'
    volumes:
      - /sessions
  ftp:
    image: stilliard/pure-ftpd:latest    
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=${FTP_USER_NAME}
      - FTP_USER_PASS=${FTP_USER_PASS}
      - FTP_USER_HOME=${FTP_USER_HOME}
      - FTP_USER_UID=${WEB_UID}
      - FTP_USER_GID=${WEB_GID}
      - FTP_PASSIVE_PORTS=${FTP_PASSIVE_PORT_BEGIN}:${FTP_PASSIVE_PORT_END}
      - TLS_USE_DSAPRAM=true
    volumes:
      - '${PROJECT_WEB_DIR}:/var/www/html'
      - './storage/ftp:/etc/ssl/private'
    ports:
      - '${FTP_PORT}:21'
      - '${FTP_PASSIVE_PORT_BEGIN}-${FTP_PASSIVE_PORT_END}:${FTP_PASSIVE_PORT_BEGIN}-${FTP_PASSIVE_PORT_END}'      